FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html menu.html checkout.html thank-you.html login.html register.html styles.css app.js checkout.js food-images.js /usr/share/nginx/html/
COPY hero.jpg about-chef.jpg /usr/share/nginx/html/
EXPOSE 80
